version: '3'

services:
  backend-login:
    build: .
    env_file:
      - .env.replica
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    restart: always