CREATE DATABASE TiCentral;
CREATE USER 'TIAdmin'@'%' IDENTIFIED BY 'FusoY8QI2oKEfAW688SeKAy3bu8I27';
CREATE USER 'TIConsulta'@'%' IDENTIFIED BY 'FaQ72efEka1AY3Nid22a7iyakIwiT8';

GRANT ALL PRIVILEGES ON TiCentral.* TO 'TIAdmin'@'%';
GRANT SELECT ON TiCentral.* TO 'TIConsulta'@'%';

FLUSH PRIVILEGES;
SHOW GRANTS FOR 'TIAdmin'@'%';
